apiVersion: v1
kind: Service
metadata:
  name: {{ include "sickchill.fullname" . }}
  labels:
    {{- include "sickchill.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
      name: sickchill
  selector:
    {{- include "sickchill.selectorLabels" . | nindent 4 }}
