apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonarr.fullname" . }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8989
      protocol: TCP
      name: sonarr
  selector:
    {{- include "sonarr.selectorLabels" . | nindent 4 }}
