apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ default 80 .Values.service.port }}
      targetPort: 9091
      protocol: TCP
      name: transmission
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
